name: conftest
on:
  push:
  workflow_dispatch:
jobs:
  conftest:
    runs-on: ubuntu-latest
    name: conftest
    steps:
      - uses: actions/checkout@v2
      - uses: terbolous/action-setup-conftest@main
      - run: conftest